/* Generated By:JavaCC: Do not edit this line. AnalisadorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalisadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPERADOR = 5;
  /** RegularExpression Id. */
  int ponto_virg = 6;
  /** RegularExpression Id. */
  int num_int = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<OPERADOR>",
    "\";\"",
    "<num_int>",
    "\"(\"",
    "\")\"",
  };

}
